feat: add `aws_ecr_repository_policy`
snyk/driftctl-docs pull request #240
Opened 2022-05-10 18:43 UTC by almog27

2022-05-11 10:52 UTC, sundowndev-snyk requested changes

2022-05-11 10:52 UTC, sundowndev-snyk commented on docs/providers/aws/authentication.mdx
> +                "ecr:GetRepositoryPolicy"
This action should be added to the Terraform custom role as well

2022-05-15 10:04 UTC, almog27 commented on docs/providers/aws/authentication.mdx
> +                "ecr:GetRepositoryPolicy"
Thanks, I missed that.

2022-06-07 11:22 UTC, sundowndev-snyk approved these changes

2022-06-08 08:26 UTC, merged