docs: add comma in list
snyk/driftctl-docs pull request #244
Opened 2022-06-22 15:17 UTC by leoalves100

2022-06-22 15:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/snyk/driftctl-docs?pullRequest=244) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/snyk/driftctl-docs?pullRequest=244) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/snyk/driftctl-docs?pullRequest=244) it.</sub>

2022-06-23 08:34 UTC, eliecharra requested changes
Thanks for the catch on `ecr:GetRepositoryPolicy`, but for the latest elements we should not have a comment, could you fix that ?

Thanks 😃

2022-06-23 08:34 UTC, eliecharra commented on versioned_docs/version-0.34.0/providers/aws/authentication.mdx
> +                "elasticloadbalancing:DescribeListeners",
The latest element of an array should not have a comma

2022-06-23 08:34 UTC, eliecharra commented on versioned_docs/version-0.34.0/providers/aws/authentication.mdx
> +      "elasticloadbalancing:DescribeListeners",
The latest element of an array should not have a comma

2022-06-23 08:50 UTC, wbeuil requested changes

2022-06-23 08:50 UTC, wbeuil commented on versioned_docs/version-0.34.0/providers/aws/authentication.mdx
> +      "ecr:GetRepositoryPolicy",
Good catch !

2022-06-23 08:50 UTC, wbeuil commented on versioned_docs/version-0.34.0/providers/aws/authentication.mdx
> +      "elasticloadbalancing:DescribeListeners",
The last policy does not need a comma, you can remove this one and the other one.

2022-06-23 08:53 UTC, wbeuil commented
Please refer to the first reviewer :)

2022-07-05 08:49 UTC, wbeuil commented
I'm gonna close this one to only merge [the other one](https://github.com/snyk/driftctl-docs/pull/245)

2022-07-05 08:49 UTC, closed without merging